{{- if and .Values.controller.enabled (not .Values.etcHosts.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ouroboros.fullname" . }}
  labels:
    {{- include "ouroboros.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "ouroboros.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ouroboros.selectorLabels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ouroboros.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          image: {{ include "ouroboros.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - controller
            - --mode=coredns
            - --coredns-namespace={{ .Values.controller.coredns.namespace }}
            - --coredns-configmap={{ .Values.controller.coredns.configmap }}
            - --coredns-key={{ .Values.controller.coredns.key }}
            - --proxy-fqdn={{ include "ouroboros.proxyFqdn" . }}
            - --resync={{ .Values.controller.resync }}
            {{- if .Values.controller.gatewayApi.enabled }}
            - --gateway-api
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
