{{- if eq (include "ouroboros.mode" .) "coredns" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ouroboros.fullname" . }}-coredns
  namespace: {{ .Values.controller.coredns.namespace }}
  labels:
    {{- include "ouroboros.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["{{ .Values.controller.coredns.configmap }}"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ouroboros.fullname" . }}-coredns
  namespace: {{ .Values.controller.coredns.namespace }}
  labels:
    {{- include "ouroboros.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ouroboros.fullname" . }}-coredns
subjects:
  - kind: ServiceAccount
    name: {{ include "ouroboros.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
