package config_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/lexfrei/ouroboros/internal/config"
)

func TestDetectClusterDomain(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		contents string
		want     string
	}{
		{
			name: "canonical kubelet emission resolves to cluster.local",
			contents: "nameserver 10.96.0.10\n" +
				"search default.svc.cluster.local svc.cluster.local cluster.local\n" +
				"options ndots:5\n",
			want: config.DefaultClusterDomain,
		},
		{
			name: "custom kubelet --cluster-domain=cozy.local resolves to cozy.local",
			contents: "nameserver 10.96.0.10\n" +
				"search default.svc.cozy.local svc.cozy.local cozy.local\n" +
				"options ndots:5\n",
			want: testCozyLocal,
		},
		{
			name: "trailing dots on search entries are stripped",
			contents: "nameserver 10.96.0.10\n" +
				"search default.svc.cluster.local. svc.cluster.local. cluster.local.\n" +
				"options ndots:5\n",
			want: config.DefaultClusterDomain,
		},
		{
			name: "extra dnsConfig.searches entries do not displace the cluster domain",
			contents: "nameserver 10.96.0.10\n" +
				"search default.svc.cluster.local svc.cluster.local cluster.local example.com internal.corp\n" +
				"options ndots:5\n",
			want: config.DefaultClusterDomain,
		},
		{
			name: "extra entries placed BEFORE the cluster-domain entries still resolve correctly",
			contents: "nameserver 10.96.0.10\n" +
				"search example.com default.svc.cluster.local svc.cluster.local cluster.local\n" +
				"options ndots:5\n",
			want: config.DefaultClusterDomain,
		},
		{
			name: "search line with tab separator parses (kubelet emits whitespace, not strict spaces)",
			contents: "nameserver\t10.96.0.10\n" +
				"search\tdefault.svc.cluster.local\tsvc.cluster.local\tcluster.local\n",
			want: config.DefaultClusterDomain,
		},
		{
			name: "comments and blank lines are tolerated",
			contents: "# Generated by kubelet\n" +
				"\n" +
				"nameserver 10.96.0.10\n" +
				"\n" +
				"search default.svc.k8s.example.org svc.k8s.example.org k8s.example.org\n",
			want: testK8sExampleOrg,
		},
		{
			name: "nameserver-only resolv.conf falls back to default cluster.local",
			contents: "nameserver 8.8.8.8\n" +
				"nameserver 1.1.1.1\n",
			want: config.DefaultClusterDomain,
		},
		{
			name:     "empty file falls back to default cluster.local",
			contents: "",
			want:     config.DefaultClusterDomain,
		},
		{
			name: "search line with only the cluster-domain (no svc.X siblings) is ambiguous, falls back to default",
			contents: "nameserver 10.96.0.10\n" +
				"search example.com\n",
			// Without any "<x>.svc.<domain>" or "svc.<domain>" sibling
			// to anchor against, we cannot tell if "example.com" is the
			// cluster domain or just a corporate search suffix. Return
			// the conventional default rather than guessing — the bare-
			// binary operator will see the chosen value in the startup
			// log and can override with --cluster-domain explicitly.
			want: config.DefaultClusterDomain,
		},
		{
			name: "multi-segment cluster domain (k8s.example.com) resolves correctly",
			contents: "nameserver 10.96.0.10\n" +
				"search ns.svc.k8s.example.com svc.k8s.example.com k8s.example.com\n",
			want: testK8sExampleCom,
		},
		{
			name: "parent zone in dnsConfig.searches does not displace the cluster domain (regression: scoring used to count any subdomain match)",
			contents: "nameserver 10.96.0.10\n" +
				"search default.svc.k8s.example.org svc.k8s.example.org k8s.example.org example.org\n",
			// example.org is the parent of k8s.example.org and would
			// score 3 if scoring counted any subdomain match (every
			// other entry ends with `.example.org`). The kubelet
			// anchor is `<x>.svc.<domain>` / `svc.<domain>` only;
			// example.org has neither, so it must score 0 and lose
			// to k8s.example.org.
			want: testK8sExampleOrg,
		},
		{
			name: "older single-domain `domain` directive is intentionally ignored (not what kubelet emits)",
			contents: "nameserver 10.96.0.10\n" +
				"domain cluster.local\n",
			// The `domain` directive is the BSD-era single-domain form
			// and is NOT what kubelet injects. Hand-edited resolv.conf
			// with both `domain` and `search` is rare; we ignore
			// `domain` so the parser cannot be confused by it.
			want: config.DefaultClusterDomain,
		},
		{
			name: "search line with single-segment entries falls back to default (no svc-anchored siblings)",
			contents: "nameserver 10.96.0.10\n" +
				"search localdomain\n",
			want: config.DefaultClusterDomain,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			path := writeTempResolvConf(t, tt.contents)

			got := config.DetectClusterDomain(path)
			if got != tt.want {
				t.Errorf("DetectClusterDomain(%q) = %q, want %q", path, got, tt.want)
			}
		})
	}
}

func TestDetectClusterDomain_FileMissing(t *testing.T) {
	t.Parallel()

	got := config.DetectClusterDomain(filepath.Join(t.TempDir(), "definitely-not-here", "resolv.conf"))
	if got != config.DefaultClusterDomain {
		t.Errorf("DetectClusterDomain on missing file = %q, want fallback %q", got, config.DefaultClusterDomain)
	}
}

func TestDetectClusterDomain_FileUnreadable(t *testing.T) {
	t.Parallel()

	// Create a directory at a path where the function would try to open
	// a file. os.Open on a directory returns no error (Go's os.Open works
	// on directories), so we simulate unreadability via a permission-
	// denied file. On platforms where this cannot be set up reliably
	// (CI as root), the test is best-effort and skips.
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	writeErr := os.WriteFile(path, []byte("search foo.svc.cluster.local svc.cluster.local cluster.local\n"), 0o000)
	if writeErr != nil {
		t.Fatalf("setup: write resolv.conf: %v", writeErr)
	}

	// Verify the file is actually unreadable (root in CI sidesteps perm
	// checks; in that case, skip the assertion).
	file, openErr := os.Open(path)
	if openErr == nil {
		file.Close()
		t.Skip("test environment ignores file permissions (likely running as root); skipping unreadable-file check")
	}

	got := config.DetectClusterDomain(path)
	if got != config.DefaultClusterDomain {
		t.Errorf("DetectClusterDomain on unreadable file = %q, want fallback %q", got, config.DefaultClusterDomain)
	}
}

func TestDetectClusterDomain_EmptyPathUsesCanonicalLocation(t *testing.T) {
	t.Parallel()

	// path == "" should fall back to the canonical /etc/resolv.conf. We
	// do not control that file in tests, so we only assert that the
	// function returns SOMETHING non-empty. (On a developer laptop the
	// returned value is whatever the host's resolv.conf says — typically
	// not "cluster.local" — so we cannot pin a specific value here.)
	got := config.DetectClusterDomain("")
	if got == "" {
		t.Error("DetectClusterDomain(\"\") returned empty; expected at least the fallback default")
	}
}

func TestClusterDomainMismatch(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		clusterDomain string
		proxyFQDN     string
		wantMismatch  bool
	}{
		{
			name:          "consistent: cluster-domain suffix matches ProxyFQDN",
			clusterDomain: "cluster.local",
			proxyFQDN:     "ouroboros-proxy.ouroboros.svc.cluster.local.",
			wantMismatch:  false,
		},
		{
			name:          "consistent: custom cluster-domain matches",
			clusterDomain: testCozyLocal,
			proxyFQDN:     testProxyFQDNCozyTenant,
			wantMismatch:  false,
		},
		{
			name:          "mismatch: cluster-domain is cozy.local but ProxyFQDN ends in cluster.local",
			clusterDomain: testCozyLocal,
			proxyFQDN:     testProxyFQDNClusterRoot,
			wantMismatch:  true,
		},
		{
			name:          "mismatch: cluster-domain is cluster.local but ProxyFQDN ends in cozy.local",
			clusterDomain: config.DefaultClusterDomain,
			proxyFQDN:     testProxyFQDNCozyTenant,
			wantMismatch:  true,
		},
		{
			name:          "no mismatch reportable: empty cluster-domain (auto-detect failed)",
			clusterDomain: "",
			proxyFQDN:     testProxyFQDNClusterRoot,
			wantMismatch:  false,
		},
		{
			name:          "no mismatch reportable: empty ProxyFQDN (mode without rewrite, e.g. external-dns)",
			clusterDomain: config.DefaultClusterDomain,
			proxyFQDN:     "",
			wantMismatch:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := config.ClusterDomainMismatch(tt.clusterDomain, tt.proxyFQDN)
			if got != tt.wantMismatch {
				t.Errorf("ClusterDomainMismatch(%q, %q) = %v, want %v", tt.clusterDomain, tt.proxyFQDN, got, tt.wantMismatch)
			}
		})
	}
}

// writeTempResolvConf writes contents to a tempdir-scoped resolv.conf and
// returns the path. The tempdir is cleaned up automatically when the test
// finishes.
func writeTempResolvConf(t *testing.T, contents string) string {
	t.Helper()

	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")

	writeErr := os.WriteFile(path, []byte(contents), 0o600)
	if writeErr != nil {
		t.Fatalf("write temp resolv.conf: %v", writeErr)
	}

	return path
}
